services:
  app:
    build: .
    container_name: post-generator-ai
    image: post-generator-ai:latest
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://127.0.0.1:8000/"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s
